consumes:
- application/json
definitions:
  MyResult:
    description: The result of an operation (default view)
    example:
      value: 1.8875258e+18
    properties:
      value:
        description: Results value
        example: 1.8875258e+18
        format: int64
        type: integer
    title: 'Mediatype identifier: vnd.my.result; view=default'
    type: object
  MyUser:
    description: MyUser media type (default view)
    example:
      email: Quas in id asperiores expedita.
      name: Aliquam recusandae ut quod id rerum.
      phone: Est corrupti molestiae et beatae asperiores perferendis.
    properties:
      email:
        description: User's email address
        example: Quas in id asperiores expedita.
        type: string
      name:
        description: User's name
        example: Aliquam recusandae ut quod id rerum.
        type: string
      phone:
        description: Phone's number
        example: Est corrupti molestiae et beatae asperiores perferendis.
        type: string
    title: 'Mediatype identifier: vnd.my.user; view=default'
    type: object
  MyUserCollection:
    description: MyUserCollection is the media type for an array of MyUser (default
      view)
    example:
    - email: Quas in id asperiores expedita.
      name: Aliquam recusandae ut quod id rerum.
      phone: Est corrupti molestiae et beatae asperiores perferendis.
    items:
      $ref: '#/definitions/MyUser'
    title: 'Mediatype identifier: vnd.my.user; type=collection; view=default'
    type: array
  user:
    example:
      email: Voluptates similique ratione.
      name: Soluta repellat.
      phone: Eos velit provident excepturi.
    properties:
      email:
        description: User's email address
        example: Voluptates similique ratione.
        type: string
      name:
        description: User's name
        example: Soluta repellat.
        type: string
      phone:
        description: Phone's number
        example: Eos velit provident excepturi.
        type: string
    required:
    - email
    - name
    title: user
    type: object
host: localhost:8080
info:
  title: Users Management
  version: ""
paths:
  /results/sum/{left}/{right}:
    get:
      description: Sum
      operationId: Operands#sum
      parameters:
      - description: Left operand
        in: path
        name: left
        required: true
        type: integer
      - description: Right operand
        in: path
        name: right
        required: true
        type: integer
      produces:
      - vnd.my.result
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/MyResult'
      schemes:
      - http
      summary: sum Operands
      tags:
      - Operands
  /users/add223344:
    post:
      description: Register a new user
      operationId: Users#add222
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/user'
      responses:
        "201":
          description: Created
      schemes:
      - http
      summary: add222 Users
      tags:
      - Users
  /users/detail/{id}:
    get:
      description: Get detail of user
      operationId: Users#detail
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - vnd.my.user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/MyUser'
      schemes:
      - http
      summary: detail Users
      tags:
      - Users
  /users/list:
    get:
      description: List all users
      operationId: Users#list
      produces:
      - vnd.my.user; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/MyUserCollection'
      schemes:
      - http
      summary: list Users
      tags:
      - Users
produces:
- application/json
responses:
  Created:
    description: Created
schemes:
- http
swagger: "2.0"
