// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "My API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/linh-snoopy/go-examples/goatest/design
// --out=c:\Users\LENOVO\go\src\github.com\linh-snoopy\go-examples\goatest
// --version=v1.3.0

package app
